version: '3'

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - prostgres_final:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./DockerFile
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  prostgres_final:
