export * from './repositories/abstract.repository';
export * from './repositories/doctor.repository';
export * from './repositories/redis-lib.repository';
export * from './repositories/doctor-type.repository';
export * from './repositories/country.repository';
export * from './repositories.module';
export * from './repositories/patient.repository';
export * from './repositories/consultations.repository';
export * from './repositories/hide.repository';
